config/routes.rb
Rails.application.routes.draw do
  constraints(AdminDomainConstraint.new) do
    devise_for :admin, class_name: 'User', only: [:sessions], controllers: {
      sessions: 'admin/sessions'
    }

    namespace :admin do
      resources :member_levels
      # resources :home, only: [:index]
      resources :items do
        member do
          patch :start
          patch :pause
          patch :end
          patch :cancel
        end
      end
      resources :categories
      resources :tickets do
        member do
          patch :cancel
        end
      end

      resources :winners, only: [:index] do
        member do
          post :submit
          post :pay
          post :ship
          post :deliver
          post :publish
          post :remove_publish
          post :re_publish
        end
      end

      resources :offers

      resources :orders, only: [:index] do
        member do
          post :pay
          post :cancel
        end
      end

      resources :users, only: [] do
        collection do
          get :invite_list
          get :user_list
        end
      end

      resources :news_tickers
      resources :banners

      resources :users, only: :index, path: 'users/clients' do
        member do
          resources :orders, only: [] do
            collection do
              get 'increase/new', to: 'balances#new_increase', as: :new_increase
              post 'increase', to: 'balances#create_increase', as: :create_increase

              get 'deduct/new', to: 'balances#new_deduct', as: :new_deduct
              post 'orders/deduct', to: 'balances#create_deduct_order', as: :create_deduct

              get 'bonus/new', to: 'balances#new_bonus', as: :new_bonus
              post 'bonus', to: 'balances#create_bonus', as: :create_bonus

              get 'member_level/new', to: 'balances#new_member_level', as: :new_member_level
              post 'member_level', to: 'balances#update_member_level', as: :update_member_level
            end
          end
        end
      end
    end
    root to: 'admin/users#index', as: :admin_root
  end

  constraints(ClientDomainConstraint.new) do
    devise_for :client, class_name: 'User', controllers: {
      sessions: 'client/sessions',
      registrations: 'client/registrations',
    }
    # Define the root within devise_scope to fix the mapping issue
    devise_scope :client do
      root to: 'client/home#new', as: :client_root
    end

    namespace :client do

      resources :shares, only: [:edit, :update, :index, :show]
      resources :home, only: [:index, :new]
      resource :me, controller: :me, only: [:show] do
        get 'order_history', to: 'me#order_history'
        get 'lottery_history', to: 'me#lottery_history'
        get 'invitation_history', to: 'me#invitation_history'
        get 'winning_history', to: 'me#winning_history'
        get 'share_feedback', to: 'me#share_feedback'
        member do
          patch :claim_prize
          post :publish
          post :cancel_order
        end
      end

      resources :locations do
        get :details
      end

      resources :lottery, only: [:index, :show] do
        member do
          post :buy_tickets
        end
      end

      resources :categories, only: [:index]

      resources :shop, only: [:index, :show] do
        member do
          post :purchase
        end
      end
      get 'invite-people', to: 'invitations#show'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: %i[index show], defaults: { format: :json } do
        resources :provinces, only: :index, defaults: { format: :json }
      end

      resources :provinces, only: %i[index show], defaults: { format: :json } do
        resources :cities, only: :index, defaults: { format: :json }
      end

      resources :cities, only: %i[index show], defaults: { format: :json } do
        resources :barangays, only: :index, defaults: { format: :json }
      end

      resources :barangays, only: %i[index show], defaults: { format: :json }
    end
  end
end

app/models/member_level.rb
class MemberLevel < ApplicationRecord
  validates :required_members, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :coins, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :user
end

app/controllers/admin/member_levels_controller.rb
class Admin::MemberLevelsController < Admin::BaseController
  before_action :set_member_level, only: [:show, :edit, :update, :destroy]

  def index
    @member_levels = MemberLevel.all
  end

  def new
    @member_level = MemberLevel.new
  end

  def create
    @member_level = MemberLevel.new(member_level_params)
    if @member_level.save
      redirect_to admin_member_levels_path, notice: 'Member level created successfully.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @member_level.update(member_level_params)
      redirect_to admin_member_levels_path, notice: 'Member level updated successfully.'
    else
      render :edit
    end
  end

  def destroy
    @member_level.destroy
    redirect_to admin_member_levels_path, notice: 'Member level deleted successfully.'
  end

  private

  def set_member_level
    @member_level = MemberLevel.find(params[:id])
  end

  def member_level_params
    params.require(:member_level).permit(:level, :required_members, :coins)
  end
end

app/views/admin/member_levels/_form.html.erb
<div class="card-body">
  <%= form_with(model: member_level, url: url, method: method, local: true, class: "row g-3") do |form| %>
    <% if member_level.errors.any? %>
      <div class="alert alert-danger">
        <h5><%= pluralize(member_level.errors.count, "error") %> prohibited this member level from being saved:</h5>
        <ul class="mb-0">
          <% member_level.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-md-4">
      <%= form.label :level, "Level", class: "form-label" %>
      <%= form.number_field :level, class: 'form-control', placeholder: "Enter level" %>
    </div>

    <div class="col-md-4">
      <%= form.label :required_members, "Required Members", class: "form-label" %>
      <%= form.number_field :required_members, class: 'form-control', placeholder: "Enter required members" %>
    </div>

    <div class="col-md-4">
      <%= form.label :coins, "Coins Reward", class: "form-label" %>
      <%= form.number_field :coins, class: 'form-control', placeholder: "Enter coins reward" %>
    </div>

    <div class="col-12">
      <%= form.submit member_level.new_record? ? "Create Member Level" : "Update Member Level", class: "btn btn-primary w-100" %>
    </div>
  <% end %>
</div>
<div class="card-footer text-end">
  <%= link_to 'Back', admin_member_levels_path, class: "btn btn-secondary" %>
</div>

app/views/admin/member_levels/edit.html.erb
<div class="container d-flex align-items-center justify-content-center vh-100">
  <div class="card w-75">
    <div class="card-header">
      <h2 class="text-center my-4">Edit Member Level</h2>
      <%= render partial: 'form', locals: { member_level: @member_level, url: admin_member_level_path,
                                            method: :patch, data: { turbo: false } } %>
    </div>
  </div>
</div>

app/views/admin/member_levels/index.html.erb
<h1 class="text-center my-4">Member Levels Management</h1>
<div class="container-fluid px-4 mt-3 w-75">
  <div class="card mb-4 mt-3">
    <div class="card-header">
      <div class="d-flex justify-content-between">
        <%= link_to 'New Member Level', new_admin_member_level_path, class: 'btn btn-primary' %>
        <%= link_to 'Back to Admin', admin_users_path, class: 'btn btn-secondary' %>
      </div>
    </div>
    <div class="card-body">
      <table class="table table-striped table-hover border rounded">
        <thead class="table-dark text-center">
        <tr>
          <th style="border-right: 1px solid #dee2e6;">Level</th>
          <th style="border-right: 1px solid #dee2e6;">Required Members</th>
          <th style="border-right: 1px solid #dee2e6;">Coins</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @member_levels.each do |member_level| %>
          <tr>
            <td class="text-center" style="border-right: 1px solid #dee2e6;"><%= member_level.level %></td>
            <td class="text-center" style="border-right: 1px solid #dee2e6;"><%= member_level.required_members %></td>
            <td class="text-center" style="border-right: 1px solid #dee2e6;"><%= member_level.coins %></td>
            <td class="text-center">
              <div class="btn-group" role="group">
                <%= link_to 'Edit', edit_admin_member_level_path(member_level), class: 'btn btn-outline-warning btn-sm' %>
                <%= button_to 'Delete', admin_member_level_path(member_level), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination justify-content-center">
        <%#= paginate @member_levels %>
      </div>
    </div>
  </div>
</div>

app/views/admin/member_levels/new.html.erb
<div class="container d-flex align-items-center justify-content-center vh-100">
  <div class="card w-75">
    <div class="card-header">
      <h2 class="text-center my-4">New Member Level</h2>
<%= render partial: 'form', locals: { member_level: @member_level, url: admin_member_levels_path, method: :post , data: {turbo: false}} %>
    </div>
  </div>
</div>